CREATE TABLE [dbo].[tbl_Requisition_Staffing] (
    [RequistionID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [DepartmentID]      INT            NOT NULL,
    [YearsofExperience] DECIMAL (18)   NULL,
    [JoiningTenure]     DECIMAL (18)   NULL,
    [NoofPositions]     INT            NULL,
    [Location]          VARCHAR (128)  NULL,
    [IsActive]          BIT            NULL,
    [Comments]          NVARCHAR (512) NULL,
    [Status]            VARCHAR (128)  NULL,
    [ManagerEmployeeID] BIGINT         NULL,
    [ManagerComments]   NVARCHAR (512) NULL,
    [CreatedBy]         BIGINT         NULL,
    [CreatedDate]       DATETIME       NULL,
    [ModifiedBy]        BIGINT         NULL,
    [ModifiedDate]      DATETIME       NULL,
    [DesignationID]     INT            NULL,
    [Title]             VARCHAR (256)  NULL,
    [RecruiterComment]  NVARCHAR (512) NULL,
    [RecruiterLeadID]   BIGINT         NULL,
    [CurrentOwner]      VARCHAR (256)  NULL,
    [ApplicantWorkFlow] NVARCHAR (MAX) NULL,
    [CancelComments]    VARCHAR (1024) NULL,
    [ClientID]          INT            NULL,
    CONSTRAINT [PK_tbl_Requisition_Staffing] PRIMARY KEY CLUSTERED ([RequistionID] ASC),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_Clients] FOREIGN KEY ([ClientID]) REFERENCES [dbo].[tbl_Clients] ([ClientID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_DepartmentMaster] FOREIGN KEY ([DepartmentID]) REFERENCES [dbo].[tbl_DepartmentMaster] ([DepartmentID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_DesignationMaster] FOREIGN KEY ([DesignationID]) REFERENCES [dbo].[tbl_DesignationMaster] ([DesignationID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_Employees] FOREIGN KEY ([ManagerEmployeeID]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_Employees1] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_Employees2] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID]),
    CONSTRAINT [FK_tbl_Requisition_Staffing_tbl_Employees3] FOREIGN KEY ([RecruiterLeadID]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID])
);

