CREATE TABLE [dbo].[tbl_Vendors] (
    [VendorID]             INT           IDENTITY (1, 1) NOT NULL,
    [VendorName]           VARCHAR (256) NULL,
    [ContactPerson]        VARCHAR (128) NULL,
    [ContactphoneNo]       INT           NULL,
    [ContactPersonEmailID] VARCHAR (256) NULL,
    [NDAStartDate]         DATETIME      NULL,
    [NDAEndDate]           DATETIME      NULL,
    [ContractEndDate]      DATETIME      NULL,
    [ContractStartDate]    DATETIME      NULL,
    [TypeofBusiness]       VARCHAR (512) NULL,
    [Specialization]       VARCHAR (512) NULL,
    [website]              VARCHAR (128) NULL,
    [AddressLine1]         VARCHAR (256) NULL,
    [AddressLine2]         VARCHAR (256) NULL,
    [City]                 VARCHAR (128) NULL,
    [State]                INT           NULL,
    [Country]              INT           NULL,
    [PinCode]              INT           NULL,
    [CreatedBy]            BIGINT        NULL,
    [ModifiedBy]           BIGINT        NULL,
    [CreatedDate]          DATE          NULL,
    [ModifiedDate]         DATE          NULL,
    [IsActive]             BIT           NULL,
    CONSTRAINT [PK_tbl_Vendors] PRIMARY KEY CLUSTERED ([VendorID] ASC),
    CONSTRAINT [FK_tbl_Vendors_tbl_Employees] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID]),
    CONSTRAINT [FK_tbl_Vendors_tbl_Employees1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[tbl_Employees] ([EmployeeID])
);

